version: "3.1"
services:
#  gobgpapi:
#    build: ./gobgp-api
#    ports:
#      - "50051:50051"
#      - "9000:9000"
#    container_name: gobgpapi
#    restart: always
#    depends_on:
#      - "sdn_controller"
  exabgpapi:
    build: ./exabgp
    ports:
      - "179:179"
      - "5001:5001"
    volumes:
      - ./exabgp/exabgp.conf:/etc/exabgp/exabgp.conf
    container_name: exabgpapi
    restart: always
    depends_on:
     - "sdn_controller"

  sdn_controller:
    build: ./sdncontroller
    ports:
      - "5000:5000"
    container_name: sdncontroller
    restart: always
    volumes:
      - ./sdncontroller/data:/app/db
