version: "3.1"
services:
  exabgpapi:
    build: ./exabgp
    ports:
      - "179:179"
      - "5001:5001"
    volumes:
      - ./exabgp/exabgp.conf:/etc/exabgp/exabgp.conf
    container_name: exabgpapi
    restart: always
    depends_on:
     - "sdn_controller"

  sdn_controller:
    build: ./sdncontroller
    ports:
      - "5000:5000"
    container_name: sdncontroller
    restart: always
    volumes:
      - sdn_db:/app/db

volumes:
  sdn_db:
