version: "3.1"
services:
  local_api:
    build: .
    ports:
      - "5000:5000"
      - "179:179"
    volumes:
      - ./exabgp/exabgp.conf:/etc/exabgp/exabgp.conf
    container_name: local_api
    restart: always

