version: "3.1"
services:
  exabgpapi:
    build: ./exabgp
    ports:
      - "179:179"
    volumes:
      - ./exabgp/exabgp.conf:/etc/exabgp/exabgp.conf
    container_name: exabgpapi
    restart: always

  sdn_controller:
    build: ./sdncontroller
    ports:
      - "5000:5000"
    container_name: sdncontroller
    restart: always

